---
title: "About Me"
---

Hi! I’m Nedret Sen Cavus, and this fall I’m beginning my Master of Science in Social Data Analytics and Research at The University of Texas at Dallas — the next step toward my dream of earning a PhD in Social Psychology and becoming a researcher–professor.

I’ve always been fascinated by how people think, feel, and act toward others — especially when group identities, social inequalities, and crisis situations are involved. My passion lies in understanding intergroup relations, social injustice, and how social identity shapes prosocial behavior.

I hold a B.A. in Psychology (Cum Laude) from Hacettepe University, and during my undergrad I spent six months at Radboud University in the Netherlands through the Erasmus+ exchange program, focusing on intergroup relations and prosocial/antisocial behavior.

I’ve also worked as a Graduate Research Assistant in Prof. Linda Tropp’s Intergroup Relations & Social Justice Lab at the University of Massachusetts Amherst, where I helped design research projects, collect and analyze data (ANOVA, regression, correlations), and explore ways to promote social cohesion between diverse groups.

Beyond the academic details, I’m someone who:

Loves diving into books and new research articles

Thrives in collaborative, idea-driven environments

## Believes data can and should be used to make the world more fair and inclusive
